const data = [
	{
		id: "panel-1",
		linkText: "Rick and Morty",
		linkHref: "#panel-1",
		class: "panel-1",
		header: "Portfolio",
		subheading: "En udforskning af frontend teknologi",
		p: "Udsigten fra mit køkken vindue",
		svg: "NightLandscape",
	},
	{
		id: "panel-2",
		linkText: "Rick and Morty",
		linkHref: "#panel-2",
		class: "panel-2",
		pageLink: "/RM",
		header: "Rick and Morty",
		subheading: "En søgbar oversigt over den animeret tv serie Rick and Morty",
		p: "Rick and Morty er en animeret tegnefilme, som følger Rick Sanchez, en super videnskabsmand og hans letpåvirkelige barnebarn Morty Smiths eventyr ",
		list: {
			header: "Frontend teknologi",
			className: "rm-technology-list-wrapper",
			items: [
				{ id: "RM01", text: "GraphQL", class: "rm-list-item" },
				{ id: "RM02", text: "Apollo Server", class: "rm-list-item" },
				{ id: "RM03", text: "Bootstrap", class: "rm-list-item" },
				{ id: "RM04", text: "React", class: "rm-list-item" },
				{ id: "RM05", text: "React Paginate", class: "rm-list-item" },
				{ id: "RM06", text: "lodash", class: "rm-list-item" },
			],
		},
		svg: "RM",
		svgBackGround: "RM",
	},
	{
		id: "panel-3",
		linkText: "Vote",
		linkHref: "#panel-3",
		class: "panel-3",
		pageLink: "/Vote",
		header: "Vote",
		subheading: "Tilkendegiv din mening",
		p: "Hvad syntes du om vores produkt?",
		list: {
			header: "Frontend teknologi",
			className: "vote-technology-list-wrapper",
			items: [
				{ id: "V01", text: "React", class: "vote-technology-list-item" },
				{ id: "V02", text: "react-inlinesvg", class: "vote-technology-list-item" },
				{ id: "V03", text: "Bootstrap", class: "vote-technology-list-item" },
			],
		},
		svg: "Likes",
	},
	{
		id: "panel-4",
		linkText: "Billede galleri",
		linkHref: "#panel-4",
		pageLink: "/Gallery",
		class: "panel-4",
		header: "Responsivt billedgalleri",
		subheading: "Swiper og Masonry",
		// p: "Mobil tilpasning af et billedgalleri, bygges som oftest ud fra en teknik, hvor de enkelte billeder bliver opstillet i horisontal række, hvor synsfeltet er afgrænset af en ramme som kun viser et lille udsnit af hele rækken. Brugeren kan nu navigere mellem de enkelte billeder ved at skyder rækkens horisontale placering og derved afdække de eller de næste billeder. Swiper er et JavaScript billedgalleri som er bygget ud fra ovenstående tanker og med mobiltilpasning i fokus",
		svg: "Gallery",
		list: {
			header: "Udsnit af frontend teknologi",
			className: "gallery-technology-list-wrapper",
			items: [
				{ id: "V01", text: "Masaon gallery", class: "vote-technology-list-item" },
				{ id: "V02", text: "Swiper gallery", class: "vote-technology-list-item" },
				{ id: "V03", text: "React", class: "vote-technology-list-item" },
			],
		},
	},
	{
		id: "panel-5",
		linkHref: "#panel-5",
		class: "panel-5",
		header: "Kontakt information og baggrund",
		eMail: "mailto:sthl@youmail.dk",
		eMailAdress: "sthl@youmail.dk",
		tlf: "45:26802420",

		list: {
			header: "CV",
			className: "vote-technology-list-wrapper",
			items: [
				{ id: "V01", text: "Portfolio", class: "vote-technology-list-item" },
				{
					id: "V02",
					toolTipHeader: "<a href='https://www.feriepartner.dk/'> Feriepartner</a>",
					popup: "Frontend udvikler hos feriepartner",
					text: "Feriepartner",
					class: "vote-technology-list-item",
				},
				{
					id: "V03",
					toolTipHeader: "Aarhus TECH",
					text: "Aarhus TECH",
					popup: "Underviser på Web-integrator og mediegrafikker uddannelsen",
					class: "vote-technology-list-item",
				},
				{
					id: "V04",
					toolTipHeader: "<a href='https://specialefag.dk'>Specialefag</a>",
					text: "Specialfag.dk",
					popup: "Udvikling af tilmeldingsportal til Mediegrafikkernes specialfag",
					class: "vote-technology-list-item",
				},
				{
					id: "V05",
					toolTipHeader: "<a href='http://www.nntv.dk/'>NNTV</a>",
					text: "Videotool.dk",
					popup: "Frontend udvikler hos NNTV: videotool.dk",
					class: "vote-technology-list-item",
				},
				{
					id: "V06",
					toolTipHeader: "Københavns tekniske skole",
					text: "Københavns tekniske skole",
					popup: "Underviser på Web-integrator og mediegrafikker uddannelsen",
					class: "vote-technology-list-item",
				},
			],
		},
	},
];
export default data;
